Updated docs to reflect the new "renderExperience" call as the main rendering entrypoint
NickelMedia/Imposium-JS-SDK pull request #86
Opened 2021-12-10 18:57 UTC by webbergreg

2021-12-11 03:09 UTC, jbmcg requested changes
Might make sense to replace the "These values will be provided to you by the Imposium team when your account and new projects are created." line near the top of the Client section with some info about where to find the access key / story ID / composition ID in the editor

2021-12-14 20:17 UTC, webbergreg commented on docs/www/client.md
> +Gets experiences by id and triggers the [`GOT_EXPERIENCE`](#GOT_EXPERIENCE) event on success. If processing an experience is intentionally deferred until after an experience is created (i.e: renderin
Change the initial copy a bit and fixed the i.e. issue

2021-12-14 20:17 UTC, webbergreg commented on docs/www/client.md
> +    videoElement.src = data.output.videos['mp4_720'].url;
Changed it to [0] anywhere it's using "renderExperience"

2021-12-14 20:17 UTC, webbergreg commented on docs/www/client.md
> +[`renderExperience`](#renderExperience) Is the easiest way to render a dynamic video and immediatly use the rendered video files. It creates a new instance of an experience, automatically kicks off t
fixed

2021-12-14 20:17 UTC, webbergreg commented on docs/www/client.md
> +Triggered when an experience record is first created. This is helpful in SPA environments for use cases where writing the id for an experience to a url can be used for SEO purposes, sharing, etc. Thi
fixed.

2021-12-14 20:17 UTC, webbergreg commented on docs/www/basic_tutorial.md
> +The above snippet will handle the end to end flow of creating video with Imposium, including playback. When `Imposium.client.renderExperience` is called the client beings listening for processed vide
fixed.

2021-12-14 20:24 UTC, jbmcg approved these changes

2021-12-17 21:17 UTC, merged